version: "3.9"

volumes:
  minio_data: {}

configs:
  # consul config
  consul_agent:
    file: consul/agent-ha.hcl
  consul_server:
    file: consul/server-ha.hcl

  # vault config
  vault_config:
    file: vault/config.hcl

  # nomad config
  nomad_client:
    file: nomad/client-ha.hcl
  nomad_server:
    file: nomad/server-ha.hcl

services:
  # minio - for asset distribution (optional)
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9090:9090"
    command:
      - server
      - /data
      - --console-address
      - ":9090"
    volumes:
      - minio_data:/data

  consul:
    image: ghcr.io/mjpitz/hashistack:latest-dind
    configs:
      - source: consul_server
        target: /etc/consul.d/server.hcl
    deploy:
      replicas: 3
    environment:
      CONSUL_ENABLED: "true"
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - "8500"
    privileged: true
    restart: always

  vault:
    image: ghcr.io/mjpitz/hashistack:latest-dind
    configs:
      - source: vault_config
        target: /etc/vault.d/config.hcl
    environment:
      VAULT_ENABLED: "true"
      VAULT_EXTRA_ARGS: "-dev"
      VAULT_DEV_ROOT_TOKEN_ID: badadmin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200"
    privileged: true
    restart: always

  nomad:
    image: ghcr.io/mjpitz/hashistack:latest-dind
    configs:
      - source: consul_agent
        target: /etc/consul.d/agent.hcl
      - source: nomad_server
        target: /etc/nomad.d/server.hcl
    depends_on:
      - consul
      - vault
    deploy:
      replicas: 3
    environment:
      CONSUL_ENABLED: "true"
      CONSUL_BIND_INTERFACE: eth0
      NOMAD_ENABLED: "true"
    ports:
      - "4646"
    privileged: true
    restart: always

  worker:
    image: ghcr.io/mjpitz/hashistack:latest-dind
    deploy:
      replicas: 3
    depends_on:
      - consul
      - vault
      - nomad
    configs:
      - source: consul_agent
        target: /etc/consul.d/agent.hcl
      - source: nomad_client
        target: /etc/nomad.d/client.hcl
    environment:
      # additional runtimes
      DOCKER_ENABLED: true
      EXTRA_PACKAGES: "openjdk11"
      # consul-configuration
      CONSUL_ENABLED: "true"
      CONSUL_BIND_INTERFACE: eth0
      # nomad configuration
      NOMAD_ENABLED: "true"
    privileged: true
    restart: always
