version: "3.9"

volumes:
  docker-certs: {}
  docker-client-certs: {}

configs:
  # consul config
  consul_agent:
    file: consul/config-agent.hcl
  consul_common:
    file: consul/config-common.hcl
  consul_server:
    file: consul/config-server.hcl

  # vault config
  vault_config:
    file: vault/config.hcl

  # nomad config
  nomad_client:
    file: nomad/config-client.hcl
  nomad_common:
    file: nomad/config-common.hcl
  nomad_server:
    file: nomad/config-server.hcl

services:
  # minio - for asset distribution (optional)
  minio:
    image: minio/minio
    ports:
      - "9090:9090"
    command:
      - server
      - /data
      - --console-address
      - ":9090"

  # docker - for running nomad job containers
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_CERT_PATH: "/certs"
    volumes:
      - docker-certs:/certs
      - docker-client-certs:/certs/client

  # server - bundles consul, vault, and nomad into a single container
  # - consul runs a server process, forming a RAFT cluster
  # - vault will run with consul as a backend and handle the administration of secrets
  # - nomad starts a server process to schedule work within the cluster
  server:
    image: hashistack:latest
    depends_on:
      - docker
    build:
      context: hashistack
    privileged: true
    configs:
      - source: consul_common
        target: /etc/consul.d/common.hcl
      - source: consul_server
        target: /etc/consul.d/server.hcl
      - source: vault_config
        target: /etc/vault.d/config.hcl
      - source: nomad_common
        target: /etc/nomad.d/common.hcl
      - source: nomad_server
        target: /etc/nomad.d/server.hcl
    volumes:
      - docker-client-certs:/certs/client:ro
    environment:
      DOCKER_TLS_VERIFY: "1"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: "/certs/client"
      CONSUL_BIND_INTERFACE: eth0
      VAULT_EXTRA_ARGS: "-dev"
      VAULT_DEV_ROOT_TOKEN_ID: badadmin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      # need -dev to support DOCKER_ environment variables
      NOMAD_EXTRA_ARGS: "-dev -bind=0.0.0.0 -client=false"
    ports:
      - "8500:8500"
      - "8200:8200"
      - "4646:4646"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # worker - bundles consul and nomad into a single container
  # - consul runs an agent process to track hosts
  # - nomad runs a client process to receive workloads
  worker:
    image: worker:latest
    depends_on:
      - server
    build:
      context: worker
    deploy:
      replicas: 3
    privileged: true
    configs:
      - source: consul_common
        target: /etc/consul.d/common.hcl
      - source: consul_agent
        target: /etc/consul.d/agent.hcl
      - source: nomad_common
        target: /etc/nomad.d/common.hcl
      - source: nomad_client
        target: /etc/nomad.d/client.hcl
    volumes:
      - docker-client-certs:/certs/client:ro
    environment:
      DOCKER_TLS_VERIFY: "1"
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: "/certs/client"
      CONSUL_BIND_INTERFACE: eth0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
