version: "3.9"

configs:
  # consul config
  consul_agent:
    file: consul/config-agent.hcl
  consul_common:
    file: consul/config-common.hcl
  consul_server:
    file: consul/config-server.hcl

  # vault config
  vault_config:
    file: vault/config.hcl

  # nomad config
  nomad_client:
    file: nomad/config-client.hcl
  nomad_common:
    file: nomad/config-common.hcl
  nomad_server:
    file: nomad/config-server.hcl

services:
  # consul - provides service discovery, health checking, and routing support.
  consul:
    image: consul:1.10
    environment:
      CONSUL_BIND_INTERFACE: eth0
    configs:
      - source: consul_common
        target: /etc/consul.d/common.hcl
      - source: consul_server
        target: /etc/consul.d/server.hcl
    ports:
      - "8500:8500"
    command:
      - agent
      - -config-dir
      - /etc/consul.d
      - -client
      - 0.0.0.0

  # vault - provides secrets management and secret engine support.
  vault:
    image: vault:1.9.0
    depends_on:
      - consul
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: badadmin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    configs:
      - source: vault_config
        target: /etc/vault.d/config.hcl
    cap_add:
      - IPC_LOCK
    command:
      - server
      - -config
      - /etc/vault.d/config.hcl
      - -dev

  # nomad - provides the nomad control plane component.
  nomad:
    image: nomad:latest
    depends_on:
      - consul
      - vault
    build:
      context: nomad
    ports:
      - "4646:4646"
    configs:
      - source: nomad_common
        target: /etc/nomad.d/common.hcl
      - source: nomad_server
        target: /etc/nomad.d/server.hcl
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command:
      -  agent
      - -config
      - /etc/nomad.d

  # worker - embeds a nomad client and a consul agent into the same container.
  # - consul is used to auto-form the Nomad cluster
  # - vault provides a CA for Consul connect and Secrets for Nomad
  worker:
    image: worker:latest
    depends_on:
      - consul
      - vault
      - nomad
    build:
      context: worker
    environment:
      CONSUL_BIND_INTERFACE: eth0
    configs:
      - source: consul_common
        target: /etc/consul.d/common.hcl
      - source: consul_agent
        target: /etc/consul.d/agent.hcl
      - source: nomad_common
        target: /etc/nomad.d/common.hcl
      - source: nomad_client
        target: /etc/nomad.d/client.hcl
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
