version: "3.9"

volumes:
  minio_data: {}
  consul_data: {}
  nomad_data: {}

configs:
  # consul config
  consul_agent:
    file: consul/agent.hcl
  consul_server:
    file: consul/server.hcl

  # nomad config
  nomad_client:
    file: nomad/client.hcl
  nomad_server:
    file: nomad/server.hcl

services:
  # minio - for asset distribution (optional)
  minio:
    image: minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9090"
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - minio_data:/data

  server:
    image: ghcr.io/mjpitz/hashistack:latest-dind
    configs:
      - source: consul_server
        target: /etc/consul.d/server.hcl
      - source: nomad_server
        target: /etc/nomad.d/server.hcl
    environment:
      # nomad runtimes
      DOCKER_ENABLED: true
      EXTRA_PACKAGES: "openjdk11"
      # consul-configuration
      CONSUL_ENABLED: "true"
      CONSUL_BIND_INTERFACE: eth0
      # vault configuration
      VAULT_ENABLED: "true"
      VAULT_EXTRA_ARGS: "-dev"
      VAULT_DEV_ROOT_TOKEN_ID: badadmin
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      # nomad configuration
      NOMAD_ENABLED: "true"
      NOMAD_EXTRA_ARGS: "-client"
    privileged: true
    ports:
      - "8500:8500"
      - "8200:8200"
      - "4646:4646"
    restart: always
    volumes:
      - consul_data:/data/consul
      - nomad_data:/data/nomad
